[project]
name = "pywebview2-frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pywebview",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
]
